logging:
  level:
    com.csxy.project.dao: DEBUG
  file:
    name: //log//jyglxt.log
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/csxy_jyglxt
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 1
    min-idle: 1
    max-active: 20
    max-wait: 60000
    validation-query: SELECT 1 FROM DUAL
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    min-evictable-idle-time-millis: 25200000
    time-between-eviction-runs-millis: 60000
    remove-abandoned: true
    remove-abandoned-timeout: 1800
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    log-abandoned: true
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
      #login-username: admin
      #login-password: admin
    filter:
      stat:
        log-slow-sql: true
        slow-sql-millis: 3000
        merge-sql: false
        enabled: false
      wall:
        config:
          multi-statement-allow: true
  redis:
    database: 6
    host: 127.0.0.1
    port: 6379
    password: csxy
    timeout: 10000
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        max-wait: -1
        min-idle: 2
